name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['user', 'product', 'order', 'transaction']
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push Docker Image
      run: |
        pwd
        cd {{ matrix.dir }}
        docker build -t ghcr.io/${{ github.repository }}/ecommerce-${{ matrix.dir }}:latest ./${{ matrix.dir }}
        docker push ghcr.io/${{ github.repository }}/ecommerce-${{ matrix.dir }}:latest
